# Distribution to use
dist: jammy
# Addons we need (e.g. docker)
addons:
  apt:
    sources:
      - sourceline: "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    packages:
      - docker

# Pre-Build
before_script:
  # Install Rust
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
  - source "$HOME/.cargo/env"

# Tasks
script:
  # Shared
  - cargo build --release --verbose --package shared
  - cargo test --release --verbose --no-default-features --no-fail-fast --package shared
  # Platform
  - cargo build --release --verbose --package platform_${TRAVIS_OS_NAME}
  - cargo test --release --verbose --no-default-features --no-fail-fast --package platform_${TRAVIS_OS_NAME}
