[package]
name = "platform_windows"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-multiplatform/Windowing-Template.git"

[dependencies]
shared = { path = "../../shared" }
