name: GitLab Mirror

on:
  push:
    branches: [ "**" ]

jobs:
  gitlab_mirror:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    # Download a mirror and push it to GitLab
    - run: |
        git clone --mirror https://github.com/rust-multiplatform/Base-Project-Template mirror_repo
        cd mirror_repo
        git push --mirror https://sakul6499:$GITLAB_TOKEN@gitlab.com/rust-multiplatform/windowing-template.git
=======
    - uses: actions/checkout@v3
    - run: git fetch --unshallow origin
    - run: git fetch --prune --all
    - run: git push --prune https://sakul6499:$GITLAB_TOKEN@gitlab.com/rust-multiplatform/base-project-template.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
>>>>>>> d68b99ff7fe9fe32ddd8e01e5a3e2fab34ba4466
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
